### ISSUE TITLE
诱导公式错误-初等数学，三角函数

### ISSUE THREAD

**Issue by eerstone** [Easymath-wiki/Easymath-wiki#15]
公式三 负角公式中好像存在bug~
sec(-\theta) = 1/ cos(-\theta) =   1/ cos(\theta) =  sec(\theta) 
csc(-\theta) = 1/ sin(-\theta) = - 1/ sin(\theta) = - csc(\theta)

**Comment by nicolaus-huang** [comment]
感谢指正，已修正
