### ISSUE TITLE
线性相关几何意义拼写错误

### ISSUE THREAD

**Issue by LiuYuan-SHU** [Easymath-wiki/Easymath-wiki#18]
在[此处](https://easymath-wiki.org/%E9%AB%98%E7%AD%89%E4%BB%A3%E6%95%B0/n%E7%BB%B4%E5%90%91%E9%87%8F%E7%A9%BA%E9%97%B4/%E7%BA%BF%E6%80%A7%E7%9B%B8%E5%85%B3%E6%80%A7%E8%B4%A8/#_7)，线性相关的几何意义中，第一个式子应当为：

$$
\lambda \vec{u} + \mu \vec{v} = \vec{0}
$$

**Comment by nicolaus-huang** [comment]
updated, thank you
